# Generated by Django 3.2.7 on 2021-10-06 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_migracion_inicial'),
        ('facturacion', '0002_renombretabla'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprobantemodel',
            name='pedido',
            field=models.OneToOneField(db_column='pedido_id', on_delete=django.db.models.deletion.CASCADE, related_name='pedidoComprobante', to='cms.pedidomodel'),
        ),
    ]
